### ISSUE TITLE
screen terminates directly

### ISSUE THREAD

**Issue by WoodyPhil** [BirknerAlex/WIFIonICE#1]
Hi, after i run "sudo python3 bin/run.py" the screen terminates after i enter my password. 

Any suggeestions why?

![image](https://user-images.githubusercontent.com/7937191/33793898-27c2aa7a-dcc1-11e7-9c2d-d364e92dc58e.png)

**Comment by BirknerAlex** [comment]
Hey,

sorry for the huge delay, never got a email for this issue :( Saw it while checking my Github projects.

If the issue still exists, start it without screen to see the error message. Maybe some python packages are missing on your system? Have you executed the pip3 install -r command?
